Added indexAll and cleanupEmpty option.
dan-online/josh-providers pull request #2
Opened 2021-03-05 19:24 UTC by c0reme

Triggers on `init()`

2021-03-05 19:45 UTC, c0reme reviewed
Functions were out of the case

2021-03-05 20:03 UTC, c0reme commented
*sigh*

2021-03-06 17:53 UTC, dan-online requested changes
Overall looks good, just a couple changes are needed

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/files.js
> +    const index = await this.getFile('index.json');
Use this.getIndex, it has checks and makes an index for you so you don't need to check for index.files

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/files.js
> +    const index = await this.getFile('index.json');
Same here

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/files.js
> +        if (!keys.includes(key)) await keys.push(key);
keys.push doesn't need an await

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/files.js
> +        if (!dataKeys.includes(key)) await keys.splice(keys.indexOf(key))
Same thing

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/index.js
> +    this.cleanupEmpty = this.options.cleanupEmpty
could this be moved to init? because we set this.options = options we can in the init() run if(this.options.indexAll), no boolean check is needed also tbh

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/index.js
> +    await this._indexAll();
only have these run if(this.options.cleanupEmpty) or if(this.options.indexAll)

2021-03-06 17:53 UTC, dan-online commented on josh-json/src/index.js
> +  }
Are these needed? Seems like we can do the indexAll check in init and then run indexAll, same for cleanupEmpty

2021-03-06 19:12 UTC, dan-online commented on josh-json/src/index.js
> +    if (typeof this.options.cleanupEmpty === 'undefined') this.options.cleanupEmpty = false;
Why is one true and the other false? also you can just do if(!this.options.indexAll)

2021-03-06 19:15 UTC, c0reme commented on josh-json/src/index.js
> +    if (typeof this.options.cleanupEmpty === 'undefined') this.options.cleanupEmpty = false;
Its for defaults and yeh that might just be better :/

2021-03-06 19:19 UTC, c0reme commented on josh-json/src/index.js
> +    if (typeof this.options.cleanupEmpty === 'undefined') this.options.cleanupEmpty = false;
I was just making it more complicated for no reason :(

2021-03-06 19:20 UTC, c0reme commented
It's good to know that my code works lol

2021-03-08 07:22 UTC, dan-online commented on josh-json/README.md
> +| [providerOptions.cleanupEmpty] | <code>boolean</code> | Optional, defaults to `false`. Cleans out empty keys from index file   |
Make sure these are correct

2021-03-13 19:17 UTC, dan-online approved these changes
Looks great!

2021-03-13 19:17 UTC, merged